#!/usr/bin/env python3
"""Build a clickable index of all Chambers Street (CSW) articles.

Reads every article in ``raw/csw/markdown/*.md``, pulls the title + URL from
frontmatter, and the publication date (frontmatter ``date`` if set, otherwise
the first ``M/D/Y`` stamp that CSW prints just under the title). Writes a
chronological, clickable catalog to ``raw/csw/index.md``.

Idempotent. Use ``--check`` to fail (exit 1) if the committed index is stale,
matching the other ``build_*.py`` CI hooks.
"""
from __future__ import annotations

import argparse
import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ARTICLES_DIR = ROOT / "raw" / "csw" / "markdown"
OUTPUT = ROOT / "raw" / "csw" / "index.md"
VIEW_OUTPUT = ROOT / "wiki" / "_views" / "csw_article_archive.md"

FM_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)
FIELD_RE = re.compile(r'^(\w+):\s*"?(.*?)"?\s*$', re.MULTILINE)
# A US-style date stamp: M/D/YY or M/D/YYYY.
DATE_RE = re.compile(r"\b(\d{1,2})/(\d{1,2})/(\d{2,4})\b")
# Already-normalized ISO date (frontmatter).
ISO_RE = re.compile(r"^(\d{4})-(\d{2})-(\d{2})$")


def parse_frontmatter(text: str) -> dict[str, str]:
    m = FM_RE.match(text)
    if not m:
        return {}
    return {k: v for k, v in FIELD_RE.findall(m.group(1))}


def body_after_frontmatter(text: str) -> str:
    m = FM_RE.match(text)
    return text[m.end():] if m else text


def extract_date(fm: dict[str, str], body: str) -> date | None:
    """Frontmatter ISO date wins; otherwise the first M/D/Y stamp near the top."""
    raw = fm.get("date", "").strip()
    iso = ISO_RE.match(raw) if raw else None
    if iso:
        try:
            return date(int(iso.group(1)), int(iso.group(2)), int(iso.group(3)))
        except ValueError:
            pass

    # CSW prints the date as the first non-empty line under the # title,
    # sometimes wrapped in emphasis / a BOM. Scan the first few such lines.
    lines = [ln.strip() for ln in body.splitlines()]
    lines = [ln for ln in lines if ln and not ln.startswith("#")]
    for ln in lines[:5]:
        m = DATE_RE.search(ln)
        if not m:
            continue
        month, day, year = (int(g) for g in m.groups())
        if year < 100:
            year += 2000 if year <= 30 else 1900
        try:
            d = date(year, month, day)
        except ValueError:
            continue
        # Guard against absurd parses from prices/percentages in prose.
        if 1990 <= d.year <= date.today().year:
            return d
    return None


def collect_rows() -> list[tuple]:
    rows = []  # (date|None, title, url, slug)
    for path in sorted(ARTICLES_DIR.glob("*.md")):
        text = path.read_text(encoding="utf-8")
        fm = parse_frontmatter(text)
        title = fm.get("title", "").strip() or path.stem
        url = fm.get("url", "").strip()
        d = extract_date(fm, body_after_frontmatter(text))
        rows.append((d, title, url, path.stem))
    return rows


def _link(r) -> str:
    _, title, url, _slug = r
    label = title.replace("[", "(").replace("]", ")")
    return f"[{label}]({url})" if url else label


def render_listing(rows: list[tuple]) -> list[str]:
    """The shared body: count line, year jump-table, year sections, undated."""
    dated = [r for r in rows if r[0] is not None]
    undated = [r for r in rows if r[0] is None]
    dated.sort(key=lambda r: (r[0], r[1].lower()), reverse=True)
    undated.sort(key=lambda r: r[1].lower())

    by_year: dict[int, list] = {}
    for r in dated:
        by_year.setdefault(r[0].year, []).append(r)
    years_desc = sorted(by_year, reverse=True)

    out: list[str] = []
    out.append(
        f"{len(dated)} dated, {len(undated)} undated. "
        "Ordered newest-first within each year."
    )
    out.append("")

    if years_desc:
        nav = "  ".join(f"[{y}](#{y})" for y in years_desc)
        if undated:
            nav += "  [Undated](#undated)"
        out.append("**Jump to:** " + nav)
        out.append("")

    for year in years_desc:
        items = by_year[year]
        out.append(f"## {year}")
        out.append("")
        out.append(f"_{len(items)} article{'s' if len(items) != 1 else ''}_")
        out.append("")
        for r in items:
            out.append(f"- `{r[0].isoformat()}` — {_link(r)}")
        out.append("")

    if undated:
        out.append("## Undated")
        out.append("")
        out.append(
            f"_{len(undated)} articles with no parseable date — listed alphabetically._"
        )
        out.append("")
        for r in undated:
            out.append(f"- {_link(r)}")
        out.append("")

    return out


def build_raw_index(rows: list[tuple]) -> str:
    out = [
        "# Chambers Street Articles — Index",
        "",
        "<!-- AUTO-GENERATED by scripts/build_csw_index.py — do not hand-edit. -->",
        "",
        f"Clickable catalog of all **{len(rows)}** scraped Chambers Street articles. "
        "Titles link to the live article on chambersstwines.com.",
        "",
    ]
    out += render_listing(rows)
    return "\n".join(out).rstrip() + "\n"


def build_wiki_view(rows: list[tuple]) -> str:
    out = [
        "---",
        "type: view",
        f"updated: {date.today().isoformat()}",
        'question: "What Chambers Street articles exist, and where can I read each one?"',
        f"source: raw/csw/markdown/ ({len(rows)} scraped articles)",
        "generated_by: scripts/build_csw_index.py",
        "---",
        "",
        "# CSW Article Archive",
        "",
        "<!-- AUTO-GENERATED by scripts/build_csw_index.py — do not hand-edit. -->",
        "",
        f"Browsable, clickable archive of all **{len(rows)}** Chambers Street "
        "articles scraped into `raw/csw/markdown/`. Each title links to the live "
        "article on chambersstwines.com; the local markdown lives at "
        "`raw/csw/markdown/<slug>.md`.",
        "",
        "CSW is the vault's editorial teacher (see `CLAUDE.md` source roles) — this "
        "view is the front door to that archive for browsing, while "
        "[[gap_csw_championed]], [[gap_csw_buy_candidates_2026_05]] and "
        "[[gap_csw_wk_overlay_2026_05]] are the analytical lenses over it. "
        "Regenerate with `python scripts/build_csw_index.py`.",
        "",
    ]
    out += render_listing(rows)
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if regenerating either output would change the committed file",
    )
    args = ap.parse_args()

    rows = collect_rows()
    targets = [
        (OUTPUT, build_raw_index(rows)),
        (VIEW_OUTPUT, build_wiki_view(rows)),
    ]

    if args.check:
        stale = False
        for path, content in targets:
            existing = path.read_text(encoding="utf-8") if path.exists() else ""
            if existing != content:
                print(f"{path.relative_to(ROOT)} is stale — run build_csw_index.py", file=sys.stderr)
                stale = True
            else:
                print(f"{path.relative_to(ROOT)} is up to date")
        return 1 if stale else 0

    for path, content in targets:
        path.write_text(content, encoding="utf-8")
        print(f"Wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
