#!/usr/bin/env python3
"""
build_ratings_board.py — roll the per-producer `## Critic Ratings` tables
(landed by compile_auction_ratings.py, ~657 rows across ~72 pages) up into one
ranked view: wiki/_views/critic_ratings_board_<YYYY_MM>.md.

The ratings data is already in the vault but only ever readable one producer at
a time. This surfaces it as a board: highest-scored wines first, flagged by
whether they're currently *buyable* at a vault retailer (Raeders/DTE/Fass
`in_portfolio` frontmatter), with region + source provenance.

Idempotent. `--check` exits 1 if regenerating would change the file.

Usage:
    python scripts/build_ratings_board.py            # write
    python scripts/build_ratings_board.py --check     # CI gate
"""
from __future__ import annotations
import re, sys
from pathlib import Path
from datetime import date

VAULT = Path(__file__).resolve().parent.parent
PROD = VAULT / "wiki" / "producers"
OUT = VAULT / "wiki" / "_views" / "critic_ratings_board_2026_07.md"

FM_RE = re.compile(r"^---\n(.*?)\n---\n(.*)$", re.DOTALL)
SECT_RE = re.compile(r"## Critic Ratings\n(.*?)(?=\n## |\Z)", re.DOTALL)
ROW_RE = re.compile(r"^\|\s*(.*?)\s*\|\s*(.*?)\s*\|\s*(.*?)\s*\|\s*(.*?)\s*\|\s*(.*?)\s*\|\s*(.*?)\s*\|$")


def get(fm: str, key: str) -> str:
    m = re.search(rf'^{key}:\s*"?([^"\n]*)"?\s*$', fm, re.MULTILINE)
    return m.group(1).strip() if m else ""


def in_portfolio(fm: str, retailer: str) -> bool:
    # match the `<retailer>:` block under `retailers:` then its in_portfolio bool
    m = re.search(rf"\n  {retailer}:\n(?:    [^\n]*\n)*?    in_portfolio:\s*(true|false)", fm)
    return bool(m and m.group(1) == "true")


def score_num(s: str):
    """'96+', '92-94', '100', 'NV' -> a sortable float (upper bound of range)."""
    s = s.strip()
    m = re.findall(r"\d+", s)
    if not m:
        return None
    if "-" in s and len(m) >= 2:
        return float(m[-1])       # range upper bound
    return float(m[0]) + (0.5 if s.endswith("+") else 0.0)


def main() -> int:
    rows = []           # (score_num, score_disp, wine, vint, producer, region, buyable, source)
    prod_stats = {}     # slug -> [name, region, count_ge95, best]
    n_pages = 0
    for path in sorted(PROD.glob("*.md")):
        text = path.read_text(encoding="utf-8", errors="replace").replace("\r\n", "\n")
        m = FM_RE.match(text)
        if not m:
            continue
        fm, body = m.group(1), m.group(2)
        sect = SECT_RE.search(body)
        if not sect:
            continue
        n_pages += 1
        name = get(fm, "name") or path.stem
        region = get(fm, "region")
        buyable = any(in_portfolio(fm, r) for r in ("raeders", "dte", "fass"))
        best = 0.0; cnt95 = 0
        for line in sect.group(1).splitlines():
            rm = ROW_RE.match(line.strip())
            if not rm:
                continue
            wine, vint, critic, score, note, source = rm.groups()
            if wine.lower() in ("wine", "---", ":---") or set(wine) <= {"-", ":"}:
                continue
            sn = score_num(score)
            if sn is None:
                continue
            rows.append((sn, score.strip(), wine, vint, name, path.stem, region, buyable, source.strip()))
            best = max(best, sn)
            if sn >= 95:
                cnt95 += 1
        if best:
            prod_stats[path.stem] = [name, region, cnt95, best]

    rows.sort(key=lambda r: (-r[0], r[4], r[2]))
    total = len(rows)
    buyable_hi = [r for r in rows if r[0] >= 96 and r[7]]

    L = []
    L.append("---")
    L.append("type: view")
    L.append(f"updated: {date.today().isoformat()}")
    L.append('question: "Across every landed critic rating, what are the highest-scored wines — and which can I actually buy right now?"')
    L.append("source: rollup of the per-producer `## Critic Ratings` sections (auction catalogs + Raeders 2026-04-25), generated by scripts/build_ratings_board.py")
    L.append("snapshot_date: 2026-04-25  # Raeders rows; auction rows are 261W W25-W30 (2026-06/07)")
    L.append("---")
    L.append("")
    L.append("# Critic Ratings Board (2026-07)")
    L.append("")
    L.append(f"Every landed critic rating in the vault, ranked. **{total} rating rows** across "
             f"**{n_pages} producers** — data that until now lived one producer at a time in each "
             f"page's `## Critic Ratings` table. Auto-generated by `scripts/build_ratings_board.py` "
             f"(re-run after `compile_auction_ratings.py`); don't hand-edit.")
    L.append("")
    L.append("- **Score** = the critic score as landed (auction notes are mostly unattributed Wine "
             "Advocate/Vinous excerpts; Raeders rows carry WA/JS/W&S/WE). Ranges sort by upper bound.")
    L.append("- **Buy?** = ✅ if the producer is flagged `in_portfolio` at a vault retailer "
             "(Raeders / DTE / Fass) in frontmatter. Prices/availability go stale — confirm before buying.")
    L.append("- Provenance in the **Source** column: `261W·Wnn lot` = Acker 261W auction week; "
             "`Raeders 2026-04-25` = the Raeders score snapshot.")
    L.append("")
    L.append(f"## Buyable now, 96+ ({len(buyable_hi)})")
    L.append("")
    L.append("The shortlist: top-scored **and** currently carried by a vault retailer.")
    L.append("")
    L.append("| Score | Wine | Vint. | Producer | Region | Source |")
    L.append("|---:|---|---|---|---|---|")
    for sn, sd, wine, vint, name, slug, region, buy, source in buyable_hi[:60]:
        L.append(f"| {sd} | {wine} | {vint or '—'} | [[{slug}\\|{name}]] | {region} | {source} |")
    L.append("")
    L.append("## Highest-scored overall — top 50")
    L.append("")
    L.append("| Score | Buy? | Wine | Vint. | Producer | Region | Source |")
    L.append("|---:|:---:|---|---|---|---|---|")
    for sn, sd, wine, vint, name, slug, region, buy, source in rows[:50]:
        L.append(f"| {sd} | {'✅' if buy else '—'} | {wine} | {vint or '—'} | [[{slug}\\|{name}]] | {region} | {source} |")
    L.append("")
    L.append("## Deepest benchmark producers (most 95+ wines)")
    L.append("")
    L.append("| Producer | Region | 95+ wines | Best |")
    L.append("|---|---|---:|---:|")
    for slug, (name, region, cnt95, best) in sorted(prod_stats.items(), key=lambda kv: (-kv[1][2], -kv[1][3]))[:25]:
        if cnt95 == 0:
            continue
        bd = f"{best:.0f}".rstrip("0").rstrip(".") if best == int(best) else f"{best}"
        L.append(f"| [[{slug}\\|{name}]] | {region} | {cnt95} | {int(best)} |")
    L.append("")

    content = "\n".join(L)
    if "--check" in sys.argv:
        cur = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if cur != content:
            print(f"DRIFT: {OUT.name} would change — re-run build_ratings_board.py")
            return 1
        print(f"OK: {OUT.name} up to date ({total} rows, {n_pages} producers)")
        return 0
    OUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUT} — {total} rating rows across {n_pages} producers "
          f"({len(buyable_hi)} buyable 96+)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
