#!/usr/bin/env python3
"""Build wiki/_views/_index.md — a catalog of every keeper-answer view page.

The main wiki index (scripts/build_wiki_index.py) deliberately skips the
_views/ directory (it's in that script's SKIP_DIRS), so views have no
catalog there. This builds the single read surface for views: one table,
sorted, with each page's question/title and last-updated date.

Idempotent. Run with --check to fail (exit 1) if the on-disk index is stale.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

VIEWS_DIR = Path(__file__).resolve().parent.parent / "wiki" / "_views"
INDEX = VIEWS_DIR / "_index.md"
FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n?(.*)$", re.DOTALL)


def parse(path: Path) -> tuple[str, str]:
    """Return (title, updated) for a view page."""
    text = path.read_text(encoding="utf-8")
    fm: dict[str, str] = {}
    body = text
    m = FRONTMATTER_RE.match(text)
    if m:
        body = m.group(2)
        for line in m.group(1).splitlines():
            if ":" in line and not line.startswith(" "):
                k, _, v = line.partition(":")
                fm[k.strip()] = v.strip().strip('"').strip("'")
    title = fm.get("question", "").strip()
    if not title:
        for line in body.splitlines():
            if line.startswith("# "):
                title = line[2:].strip()
                break
    if not title:
        title = path.stem.replace("_", " ")
    return title, fm.get("updated", "")


def build() -> str:
    rows = []
    for p in sorted(VIEWS_DIR.glob("*.md")):
        if p.name == INDEX.name:
            continue
        title, updated = parse(p)
        # escape pipes so the markdown table doesn't break
        title = title.replace("|", "\\|")
        rows.append(f"| [[{p.stem}|{p.stem}]] | {title} | {updated} |")
    lines = [
        "---",
        "type: index",
        "generator: scripts/build_views_index.py",
        "---",
        "",
        "# Views Index",
        "",
        "<!-- Generated by `scripts/build_views_index.py`. Do not hand-edit. -->",
        "",
        "Catalog of every keeper-answer page in `wiki/_views/` — the single "
        "read surface for saved analyses (gap analysis, drink-window "
        "shortlists, cross-retailer comparisons, critic overlays). The main "
        "`wiki/index.md` skips this directory, so this is where views are "
        "cataloged.",
        "",
        f"**{len(rows)} views.**",
        "",
        "| Page | Question / title | Updated |",
        "|---|---|---|",
        *rows,
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    content = build()
    if "--check" in sys.argv:
        current = INDEX.read_text(encoding="utf-8") if INDEX.exists() else ""
        if current != content:
            print("STALE: wiki/_views/_index.md is out of date — re-run "
                  "scripts/build_views_index.py", file=sys.stderr)
            return 1
        print("OK: wiki/_views/_index.md is current.")
        return 0
    INDEX.write_text(content, encoding="utf-8")
    n = content.count("\n| [[")
    print(f"Wrote {INDEX} ({n} views)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
